export const COLOR_PROPERTIES = {
  backgroundColor: 'color',
  border: 'color',
  borderColor: 'color',
  borderStartColor: 'color',
  borderEndColor: 'color',
  borderTopColor: 'color',
  borderLeftColor: 'color',
  borderBottomColor: 'color',
  borderRightColor: 'color',
  color: 'color',
  tintColor: 'color',
  shadowColor: 'color',
  textShadowColor: 'color',
  textDecoration: 'color',
  overlayColor: 'color',
};

export const RADII_PROPERTIES = {
  borderRadius: 'radii',
  borderTopLeftRadius: 'radii',
  borderTopRightRadius: 'radii',
  borderBottomRightRadius: 'radii',
  borderBottomLeftRadius: 'radii',
};

export const SPACE_PROPERTIES = {
  margin: 'space',
  marginTop: 'space',
  marginRight: 'space',
  marginBottom: 'space',
  marginLeft: 'space',
  marginEnd: 'space',
  marginStart: 'space',
  marginHorizontal: 'space',
  marginVertical: 'space',
  padding: 'space',
  paddingTop: 'space',
  paddingRight: 'space',
  paddingBottom: 'space',
  paddingLeft: 'space',
  paddingHorizontal: 'space',
  paddingVertical: 'space',
  paddingEnd: 'space',
  paddingStart: 'space',
  top: 'space',
  right: 'space',
  bottom: 'space',
  left: 'space',
};

export const SIZE_PROPERTIES = {
  width: 'size',
  minWidth: 'size',
  maxWidth: 'size',
  height: 'size',
  minHeight: 'size',
  maxHeight: 'size',
  flexBasis: 'size',
};
