export const COLOR_PROPERTIES = [
  'backgroundColor',
  'border',
  'borderColor',
  'borderStartColor',
  'borderEndColor',
  'borderTopColor',
  'borderLeftColor',
  'borderBottomColor',
  'borderRightColor',
  'color',
  'tintColor',
  'shadowColor',
  'textShadowColor',
  'textDecoration',
  'overlayColor',
];

export const RADII_PROPERTIES = [
  'borderRadius',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderBottomRightRadius',
  'borderBottomLeftRadius',
];

export const SPACE_PROPERTIES = [
  'margin',
  'marginTop',
  'marginRight',
  'marginBottom',
  'marginLeft',
  'marginEnd',
  'marginStart',
  'marginHorizontal',
  'marginVertical',
  'padding',
  'paddingTop',
  'paddingRight',
  'paddingBottom',
  'paddingLeft',
  'paddingHorizontal',
  'paddingVertical',
  'paddingEnd',
  'paddingStart',
  'top',
  'right',
  'bottom',
  'left',
];

export const SIZE_PROPERTIES = [
  'width',
  'minWidth',
  'maxWidth',
  'height',
  'minHeight',
  'maxHeight',
  'flexBasis',
];
